### ISSUE TITLE
Add a proper license

### ISSUE THREAD

**Issue by ghost** [fikriomar16/obtgen#1]
Your script is awesome dude,
But according to https://choosealicense.com/, we can't use your program because there's no valid license file.
Well we're not allowed to enforce you to use a specific license text because of legal reasons. 
You as the author are encouraged to distribute the official text file to comply with :)

**Comment by fikriomar16** [comment]
Thanks so much dude
It's so helpful

**Comment by ghost** [comment]
Me too :)

Fixed by 93facff
